name: Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  update:
    name: update stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
